# Config file for automatic testing at travis-ci.org

dist: xenial
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

install: pip install 'tox-travis ~= 0.12.0'
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
