site_name: pytest-mypy
site_description: Mypy static type checker plugin for Pytest
site_author: Daniel Bader

theme: readthedocs

repo_url: https://github.com/dbader/pytest-mypy

pages:
- Home: index.md
